### ISSUE TITLE
[ENHANCEMENT] Tema non responsive nel Blog

### ISSUE THREAD

**Issue by Azzeccagarbugli** [morrolinuxyt/website#4]
Il Blog non presenta un design responsive.

**Comment by r-carissimi** [comment]
Intanto grazie per aver usato la sezione "Issiues", in secondo luogo non capisco cosa intendi... ti potresti spiegare meglio descrivendo il problema riscontrato?
Te ne saremo davvero grati. Grazie e ciao!

EDIT: Ah, ok, ho capito. Il fatto è che il blog è creato e "hostato" (anche se non sarebbe il termine più adatto) su ZeroNet, dove non è possibile modificare il tema. Le ragioni di questa scelta le abbiamo elencate nella sezione "La Scelta di Zeronet" della lettera che puoi leggere nella home. Purtroppo questo è uno svantaggio. Se hai delle soluzioni migliori saremmo felicissimi di usarle! Ciao!
