### ISSUE TITLE
Errore di rindirizzamento Blog

### ISSUE THREAD

**Issue by checcoux** [morrolinuxyt/website#5]
Andando su qualsiasi voce del menu nel sito blog.morrolinux.it, i vari link portano a una pagina non esistente.  Credo che l'intento fosse quello di renderizzare i link alle pagine del sito morrolinux.it, invece sbadatamente portano a - come avevo già accennato prima - una pagina non esistente. 

>  <ul>
            <li class="nav-home-sito" role="presentation"><a href="https://morrolinux.it">Home Sito</a></li>
            <li class="nav-blog nav-current" role="presentation"><a href="http://blog.morrolinux.it/">Blog</a></li>
            <li class="nav-progetti" role="presentation"><a href="http://blog.morrolinux.it/projects.php">Progetti</a></li>
            <li class="nav-lpi" role="presentation"><a href="http://blog.morrolinux.it/lpi.php">LPI</a></li>
            <li class="nav-about-me" role="presentation"><a href="http://blog.morrolinux.it/about.php">About Me</a></li>
            <li class="nav-sostieni" role="presentation"><a href="http://blog.morrolinux.it/sostieni.php">Sostieni</a></li>

Riporto la parte dell'html contenente i link errati

**Comment by r-carissimi** [comment]
Grazie mille per aver segnalato. 
Ho appena messo a posto tutti i link, adesso dovrebbero funzionare come prima, probabilmente l'ultimo aggiornamento di Ghost deve aver cambiato i link.
