### ISSUE TITLE
contatto

### ISSUE THREAD

**Issue by mauro-miatello** [morrolinuxyt/website#6]
ciao
nel tuo sito non c'è un form contatti per scriverti
solo per dirti, se vuoi un cms da provare, dai un'occhiata a contao.org
è molto interessante, anche se devo dire che è un po' complesso all'inizio, la versione 4 poi è un po' difficile anche da installare, più facile la 3 (ancora supportata)
complimenti per tutto e avanti così

**Comment by morrolinux** [comment]
Grazie mille!!! :) 
PS: in realtà per la natura statica del sito preferiamo mantenere nessun CMS al momento :)

**Comment by Fanto13** [comment]
ma è normale che questa mail arrivi anche a me?

2018-03-13 17:27 GMT+01:00 morrolinux <notifications@github.com>:
